apiVersion: kp.kpack.io/v1alpha3
kind: DependencyDescriptor
defaultClusterBuilder: base
defaultClusterStack: base
lifecycle:
  image: registry.pivotal.io/tbs-dependencies/lifecycle@sha256:15bb6e7262a0a07226de4d41096c2cb8e860534a6d1235d6895b5c9eb0fec74a
clusterStores:
- name: default
  sources:
  - image: registry.pivotal.io/tanzu-go-buildpack/go@sha256:e6c2829eb3194f4c5842188df288f16b99f51ae79cd9853f2f5cee0ba2d10c91
  - image: registry.pivotal.io/tanzu-java-buildpack/java@sha256:c41c54c4cc6bcd5e5b20079550d580d69ce121dfdc0b7c84ba38d06ba361e91f
  - image: registry.pivotal.io/tanzu-nodejs-buildpack/nodejs@sha256:9d9c408013328bf63751380220fdd84926d0e96bc3218929073664c0497d5b66
  - image: registry.pivotal.io/tanzu-java-native-image-buildpack/java-native-image@sha256:8f7884990dfceeef197d5c6e63884cdb6d3e73a4895f3053ada4c28100957ccb
  - image: registry.pivotal.io/tanzu-dotnet-core-buildpack/dotnet-core@sha256:d14e837c60a55e151727b2badd570759d59ad6fb0702dcde65b26f1896ab358c
  - image: registry.pivotal.io/tanzu-python-buildpack/python@sha256:3a6532ddd8e5ed475ddee72cf2f23b9b60635369677083f91d786f3dbfd9856a
  - image: registry.pivotal.io/tanzu-procfile-buildpack/procfile@sha256:baf55402599aab20c52d1c819a9a63b0c6e861e18599b23b91d1871fc11b5d25
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_php@sha256:d83cea6e08cd14511ffad09791e3cccf60f0c88a6421e6b36fbfc40b0e256f49
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_nginx@sha256:3dbb0e732135791614d3f79b9ee35c49bcdd673940bc4167d236e2160eb11cc4
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_httpd@sha256:e8f8171f65be0b81087a857d94eacef54f82420af57222c90ab4b91a9984ba45
clusterStacks:
- name: tiny
  buildImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/build@sha256:27774f4d93006356b29f3e3db51dc1a44d4efb5584ca45a64b749839b2f2b7ba
  runImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/run@sha256:4ab27a1ce530d91e03c27dc4f2e8576110fb8d8c7b05fb35716d4f226cffdf45
- name: base
  buildImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/build@sha256:b062503e410dd5aec2059721104c1bfee86b826e845fc08343ed31028588e3f6
  runImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/run@sha256:c380a7b01bb93840201271fe9ea0911c4add2af9da54e50b19ef5d6b54829fae
- name: full
  buildImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/build@sha256:f181d8f3e75b3236ba68a71ee0da1f652a2bb2d8e6b08e3488ef7e2be7ef743f
  runImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/run@sha256:c9a17cdafa2f8e115e29ada6e38eb97007cf4c0ee04eaa3805a962000434d2a8
clusterBuilders:
- name: base
  clusterStack: base
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: full
  clusterStack: full
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: tiny
  clusterStack: tiny
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: paketo-buildpacks/procfile
